# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build
      - run: npm run test:lint
      - run: npm run test:prettier

  test:
    machine:
      # We can't use a containerized environment since it requires remote docker to start custom containers.
      # However, we can't access the remote docker's network from the primary container. This is a
      # feature, as documented in https://circleci.com/docs/2.0/building-docker-images/#separation-of-environments
      # As a consequence, we cannot use the circleci CLI for this job because "You cannot use the machine
      # executor in local jobs." (https://circleci.com/docs/2.0/local-cli/#limitations-of-running-jobs-locally)
      #
      # Available images: https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: # start early for less wait time below
          name: Start wasmd
          command: ./scripts/wasmd/start.sh
          background: true
      - run: # start early for less wait time below
          name: Start gaiad
          command: ./scripts/gaia/start.sh
          background: true
      - run:
          # TODO: check if still needed with 20.04
          # The images ubuntu-1604 comes with preinstalled nvm, which does not work well with non-login shells
          name: Uninstall nvm
          # Moving to trash is faster than deleting (gvfs-trash is not installed on this image)
          command: mkdir -p ~/.local/share/Trash && mv "$NVM_DIR" ~/.npm ~/.local/share/Trash
      - run:
          name: Install nodejs
          # In the current image, `sudo apt install nodejs` requires `sudo apt update` which is too slow
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Version information
          command: echo "node $(node --version)"; echo "npm $(npm --version)"
      - restore_cache:
          name: Restore Npm Package Cache
          keys:
            - yarn-packages-{{ checksum "package-lock.json" }}
      - run: npm install --frozen-lockfile
      - run: npm run build
      - save_cache:
          name: Save Npm Package Cache
          key: yarn-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Wait for chains to start up
          command: |
            echo "Wait for wasmd..."
            timeout 60 bash -c "until curl -s http://localhost:26659/status > /dev/null; do sleep 0.5; done"
            echo "Wait for gaia..."
            timeout 60 bash -c "until curl -s http://localhost:26655/status > /dev/null; do sleep 0.5; done"
            sleep 1
            echo "Chains up and running!"
      - run:
          command: npm run test
      - run:
          name: Stop chains
          command: |
            ./scripts/wasmd/stop.sh
            ./scripts/gaia/stop.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
